<a href="https://colab.research.google.com/github/pappyjoe16/TensorFlow_lesson/blob/main/Lesson1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Installing TensorFlow **

In [8]:
!pip install tensorflow-gpu==2.2.0-alpha0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==2.2.0-alpha0 (from versions: 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.12.0)
ERROR: No matching distribution found for tensorflow-gpu==2.2.0-alpha0


## **Import required libraries**

In [12]:
import tensorflow as tf
import numpy as np

In [27]:
#geting the version
tf.__version__

'2.2.0'

In [25]:
#Defining a constant in TensorFlow
tensor_20 = tf.constant([[23.5, 4], [32, 5.1]])

In [26]:
#calling out the constant 
tensor_20

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[23.5,  4. ],
       [32. ,  5.1]], dtype=float32)>

In [28]:
#Getting the shape of the constant variable 
tensor_20.shape

TensorShape([2, 2])

In [30]:
tensor_20.numpy()

array([[23.5,  4. ],
       [32. ,  5.1]], dtype=float32)

In [31]:
#converting array to tensor
numpy_tensor = np.array([[23, 12], [13, 42]])

In [37]:
tensor_from_numpy = tf.constant(numpy_tensor)
#tensor_from_numpy
tensor_from_numpy.numpy()

array([[23, 12],
       [13, 42]])

# **Variable**

In [43]:
#Defining a variable 
tf2_variable = tf.Variable([[1, 3, 5], [2, 4, 6], [3, 5, 6]])
#Getting the variable values
#tf2_variable.numpy()
tf2_variable

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6],
       [3, 5, 6]], dtype=int32)>

In [46]:
#To change a specific value in the variable
tf2_variable[1, 1].assign(9).numpy() # [1,1] represent [row1 coloum1]

array([[1, 3, 5],
       [2, 9, 6],
       [3, 5, 6]], dtype=int32)

# **Operations with tensors**

In [47]:
#declaring a constant
tensor = tf.constant([[1, 2], [3, 4]])
tensor.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

In [48]:
#Addition between scalar(unit value, value with no dimention) and a tensor
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [49]:
#Multiplication between scalar(unit value, value with no dimention) and a tensor
tensor * 4

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4,  8],
       [12, 16]], dtype=int32)>

# **Using numpy function on tensorflow tensor**

In [50]:
#Getting the squares of all members in a tensorflow tensor object
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [51]:
#Getting the square root of all members in a tensorflow tensor object
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [52]:
#Getting the exponential of all members in a tensorflow tensor object
np.exp(tensor)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [57]:
#Dot product between two tensors
np.dot(tensor_20, tensor)

array([[35.5       , 63.        ],
       [47.29999971, 84.39999962]])

In [58]:
np.dot(tensor, tensor_20)

array([[ 87.5       ,  14.19999981],
       [198.5       ,  32.39999962]])

# **Strings in Tensorflow**

In [61]:
#Dclaring Strings
tf_string = tf.constant("Welcome to Tensorflow")
#tf_string.numpy()
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'Welcome to Tensorflow'>

In [62]:
#To get the length of the string
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [66]:
#To decode string into "UTF8"
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(21,), dtype=int32, numpy=
array([ 87, 101, 108,  99, 111, 109, 101,  32, 116, 111,  32,  84, 101,
       110, 115, 111, 114, 102, 108, 111, 119], dtype=int32)>

In [67]:
#Storing arrays of strings
tf_string_array = tf.constant(["TensorFlow", "Deep learning", "Machine learning", "AI"])

In [71]:
#Iterating through array of Strings
for string in tf_string_array:
  print(string.numpy())

b'TensorFlow'
b'Deep learning'
b'Machine learning'
b'AI'
